name: Testing

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'

      - name: Install dependencies
        run: |
          npm ci

      - name: Run Tests
        run: |
          npm run test

      - name: Run eslint
        run: |
          npm run eslint

      - name: Run stylelint
        run: |
          npm run stylelint